### PR TITLE
[SIE-152] Login page shows feedback

### PR DESCRIPTION
**Pull request by cmutuc25**
Made the login page respond based on the error message received. Error message will show on the page, if something fails, there will be 'Server not responding' message.

Added simple test to check if there's an error message if the backend function returns an error.

Removed some es lint lines.

Refactored auth-provider to provide a reload functionality to make it more obvious how to reload when a user is logged in or changed

### CODE REVIEW

**Review by fernandowinfield — APPROVED** [review]
Looks good! So now we can just use `useAuth()` instead of `useContext(AuthContext)`?

**Comment by cmutuc25** [comment]
Yes, just so we don't have to import `useContext`. Minor change

**Comment by cmutuc25** [comment]
Need to add a message if a user is has an unverified email

**Comment by cmutuc25** [comment]
Reopening this as i added the email verification error

**Comment by cmutuc25** [comment]
Reopening this as I added the email verification error

**Pull request merged**
